### ISSUE TITLE
Model accuracy of teeth_segment.tflite for teetg segmentation is not up to the mark.

### ISSUE THREAD

**Issue by Utkarsh-quytech** [DonkeySmall/Delphi-Tensorflow-Lite#6]
I used the model for teeth segmentation and wrote the code in python for inference but the accuracy of the model in some images is very low, in some cases it even does not detect teeth in the images even if the teeth is clearly visible.
Do you have some other model that has better accuracy than this one for teeth segmentation or some way to improve the accuracy of the model or some other way for teeth segmentation that might be useful.
![Figure_1](https://github.com/DonkeySmall/Delphi-Tensorflow-Lite/assets/152372849/286bf820-928b-46b6-b735-c3e6e056e1f6)
![Figure_2](https://github.com/DonkeySmall/Delphi-Tensorflow-Lite/assets/152372849/77a8e2d3-9ec0-44ee-9aa6-bbc63c0b3b51)

**Comment by DonkeySmall** [comment]
In order for the accuracy to be at a high level, the face image should occupy about 80 percent and be located in the center.
![screen](https://github.com/DonkeySmall/Delphi-Tensorflow-Lite/assets/66531939/79d733aa-c7c1-4727-925a-f27a008c2bb8)

**Comment by DonkeySmall** [comment]
![screen](https://github.com/DonkeySmall/Delphi-Tensorflow-Lite/assets/66531939/61061355-3d96-489a-8105-a07e52492031)

**Comment by Utkarsh-quytech** [comment]
Thanks for the help.
